version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    AWS_ACCOUNT_ID: "829676085607"
    IMAGE_REPO_NAME: "simple-docker-service-064a2b2a4bd5"
    CONTAINER_NAME: "simple-docker-service-064a2b2a4bd5"

phases:
  install:
    runtime-versions:
      java: corretto17 # Asegura que CodeBuild tenga Java 17 instalado
  pre_build:
    commands:
      - echo Compilando el proyecto Maven...
      - mvn clean package -DskipTests # Esto genera la > imagedefinitions.json

artifacts:
  files: imagedefinitions.json